#ifndef BCPLAY_CONF_H_SEEN
#define BCPLAY_CONF_H_SEEN

#define BC_LOG_LEVEL LOG_DEBUG
#define BC_PLAYER_USERID 1002
#define BC_KIOSK_WIDTH 960
#define BC_KIOSK_HEIGHT 600
#define BC_KIOSK_DISPLAY ":1"

#endif  // BCPLAY_CONF_H_SEEN
